### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by uknowsec** [CCob/goreflect#1]
Hello, I tried to compile this project. I first used cmake in Windows 10, and then used vs2019 to compile the project, but the following error occurred.

1. Can't find libgorefect_prog.h file

2. error MSB3073: The command "setlocal

Can you help me? Thank you very much~

**Comment by akkuman** [comment]
```
# install mingw, cmake, golang on Windows
> scoop install gcc cmake go

# generate makefile
goreflect> cmake . -G "MinGW Makefiles"

# build dll
goreflect> make
```

This operation was a success for me, I hope it can help you. @uknowsec 

By the way, your blog is very good
